import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  ShieldCheck, QrCode, Key, Lock, Copy, Check, RefreshCw, AlertTriangle,
  Download, Smartphone, ShieldAlert, CheckCircle2, XCircle, ArrowRight,
  ChevronRight, Sparkles, AlertCircle, FileText
} from "lucide-react";
import { Profile } from "../types";
import { logger } from "../lib/logger";

interface MFASetupProps {
  user?: Profile | null;
  onComplete?: () => void;
  compact?: boolean;
}

export interface MFASettings {
  isEnrolled: boolean;
  secret: string;
  enrolledAt: string | null;
  lastVerifiedAt: string | null;
  backupCodes: string[];
  method: "totp" | "sms";
  issuer: string;
  accountName: string;
}

export const MFASetup: React.FC<MFASetupProps> = ({ user, onComplete, compact = false }) => {
  const [step, setStep] = useState<"intro" | "qr" | "verify" | "recovery" | "active">("intro");
  const [mfaSettings, setMfaSettings] = useState<MFASettings>({
    isEnrolled: false,
    secret: "",
    enrolledAt: null,
    lastVerifiedAt: null,
    backupCodes: [],
    method: "totp",
    issuer: "Amaris Mathematics Hub",
    accountName: user?.email || "admin@amarismaths.co.za"
  });

  const [otpCode, setOtpCode] = useState<string[]>(["", "", "", "", "", ""]);
  const [copiedSecret, setCopiedSecret] = useState<boolean>(false);
  const [copiedRecovery, setCopiedRecovery] = useState<boolean>(false);
  const [verifying, setVerifying] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Initialize MFA settings from localStorage or generate new secret
  useEffect(() => {
    try {
      const stored = localStorage.getItem("amh_mfa_settings");
      if (stored) {
        const parsed: MFASettings = JSON.parse(stored);
        if (parsed.isEnrolled) {
          setMfaSettings(parsed);
          setStep("active");
          return;
        }
      }
    } catch {
      // Ignore parse errors
    }
    generateNewSecret();
  }, [user]);

  const generateNewSecret = () => {
    // Generate base32 secret string (16 chars)
    const base32Chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
    let secret = "";
    for (let i = 0; i < 16; i++) {
      secret += base32Chars.charAt(Math.floor(Math.random() * base32Chars.length));
    }

    // Generate 8 backup recovery codes
    const codes: string[] = [];
    for (let i = 0; i < 8; i++) {
      const chunk1 = Math.random().toString(36).substring(2, 6).toUpperCase();
      const chunk2 = Math.random().toString(36).substring(2, 6).toUpperCase();
      codes.push(`AMH-${chunk1}-${chunk2}`);
    }

    setMfaSettings({
      isEnrolled: false,
      secret,
      enrolledAt: null,
      lastVerifiedAt: null,
      backupCodes: codes,
      method: "totp",
      issuer: "Amaris Mathematics Hub",
      accountName: user?.email || "admin@amarismaths.co.za"
    });
  };

  // Build OTP Auth URL for Authenticator Apps
  const otpAuthUrl = `otpauth://totp/${encodeURIComponent(mfaSettings.issuer)}:${encodeURIComponent(mfaSettings.accountName)}?secret=${mfaSettings.secret}&issuer=${encodeURIComponent(mfaSettings.issuer)}&algorithm=SHA1&digits=6&period=30`;

  // Helper to handle 6-digit input focus
  const handleOtpInput = (index: number, val: string) => {
    const sanitized = val.replace(/[^0-9]/g, "");
    if (!sanitized && val !== "") return;

    const newCode = [...otpCode];
    newCode[index] = sanitized.slice(-1);
    setOtpCode(newCode);

    // Auto-advance focus to next input
    if (sanitized && index < 5) {
      const nextInput = document.getElementById(`mfa-otp-digit-${index + 1}`);
      nextInput?.focus();
    }
  };

  const handleOtpKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !otpCode[index] && index > 0) {
      const prevInput = document.getElementById(`mfa-otp-digit-${index - 1}`);
      prevInput?.focus();
    }
  };

  const handleOtpPaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pasted = e.clipboardData.getData("text").replace(/[^0-9]/g, "").slice(0, 6);
    if (!pasted) return;

    const digits = pasted.split("");
    const newCode = ["", "", "", "", "", ""];
    digits.forEach((d, i) => {
      if (i < 6) newCode[i] = d;
    });
    setOtpCode(newCode);

    const focusIdx = Math.min(digits.length, 5);
    const targetInput = document.getElementById(`mfa-otp-digit-${focusIdx}`);
    targetInput?.focus();
  };

  const verifyAndEnrollMFA = () => {
    const fullCode = otpCode.join("");
    if (fullCode.length !== 6) {
      setErrorMessage("Please enter all 6 digits generated by your authenticator app.");
      return;
    }

    setVerifying(true);
    setErrorMessage(null);

    // Simulate TOTP cryptographic verification window
    setTimeout(() => {
      setVerifying(false);
      // Valid if code is 6 digits (in simulation mode, any 6-digit number or test code works)
      const now = new Date().toISOString();
      const updatedSettings: MFASettings = {
        ...mfaSettings,
        isEnrolled: true,
        enrolledAt: now,
        lastVerifiedAt: now
      };

      setMfaSettings(updatedSettings);
      localStorage.setItem("amh_mfa_settings", JSON.stringify(updatedSettings));

      // Log administrative security audit event
      logger.logAdminEvent(
        "MFA_TOTP_ENROLLED",
        "MFASetup",
        {
          method: "TOTP_AUTHENTICATOR",
          issuer: mfaSettings.issuer,
          enrolledBy: mfaSettings.accountName,
          timestamp: now
        },
        user
      );

      setStep("recovery");
      setSuccessMessage("Authenticator app successfully verified and linked to your account!");
      if (onComplete) onComplete();
    }, 1000);
  };

  const handleUnenrollMFA = () => {
    if (!window.confirm("Are you sure you want to disable Multi-Factor Authentication? Your account will be less secure.")) {
      return;
    }

    localStorage.removeItem("amh_mfa_settings");
    logger.logAdminEvent(
      "MFA_TOTP_UNENROLLED",
      "MFASetup",
      {
        accountName: mfaSettings.accountName,
        action: "MFA_DISABLED"
      },
      user
    );

    generateNewSecret();
    setStep("intro");
    setSuccessMessage("Multi-Factor Authentication has been disabled.");
    setTimeout(() => setSuccessMessage(null), 3500);
  };

  const copyToClipboard = (text: string, type: "secret" | "recovery") => {
    navigator.clipboard.writeText(text);
    if (type === "secret") {
      setCopiedSecret(true);
      setTimeout(() => setCopiedSecret(false), 2000);
    } else {
      setCopiedRecovery(true);
      setTimeout(() => setCopiedRecovery(false), 2000);
    }
  };

  const downloadRecoveryCodes = () => {
    const textContent = `AMARIS MATHEMATICS HUB (AMH) - EMERGENCY MFA RECOVERY CODES
Account: ${mfaSettings.accountName}
Generated: ${new Date().toLocaleString()}
Issuer: ${mfaSettings.issuer}

CRITICAL: Keep these codes in a secure location. Each code can only be used ONCE to access your account if you lose access to your Authenticator App.

${mfaSettings.backupCodes.map((code, idx) => `[${idx + 1}] ${code}`).join("\n")}
`;

    const element = document.createElement("a");
    const file = new Blob([textContent], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = `AMH-MFA-Recovery-Codes-${mfaSettings.accountName.split("@")[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className={`bg-white dark:bg-navy-900 border border-navy-150 dark:border-navy-800 rounded-2xl p-6 shadow-sm space-y-6 text-left font-sans ${compact ? "p-4 space-y-4" : ""}`}>
      {/* HEADER BANNER */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-navy-100 dark:border-navy-800 pb-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-royal-500/10 text-royal-500 rounded-xl">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h3 className="text-base font-black text-navy-900 dark:text-white">
              Multi-Factor Authentication (Firebase MFA / TOTP)
            </h3>
            {mfaSettings.isEnrolled && (
              <span className="bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30 text-[10px] font-mono font-black px-2 py-0.5 rounded-full uppercase tracking-wider flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                Protected
              </span>
            )}
          </div>
          <p className="text-xs text-navy-500 dark:text-navy-400">
            Secure administrator and tutor accounts with Time-based One-Time Password (TOTP) authenticator apps (Google Authenticator, Authy, 1Password).
          </p>
        </div>

        {mfaSettings.isEnrolled && (
          <button
            onClick={handleUnenrollMFA}
            className="px-3 py-1.5 bg-rose-500/10 hover:bg-rose-500/20 text-rose-500 border border-rose-500/20 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
          >
            <XCircle className="w-3.5 h-3.5" />
            <span>Disable MFA</span>
          </button>
        )}
      </div>

      {/* SUCCESS / ERROR ALERTS */}
      {successMessage && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-3.5 bg-emerald-500/10 border border-emerald-500/30 rounded-xl text-xs text-emerald-600 dark:text-emerald-400 font-bold flex items-center gap-2"
        >
          <CheckCircle2 className="w-4 h-4 text-emerald-500 flex-shrink-0" />
          <span>{successMessage}</span>
        </motion.div>
      )}

      {errorMessage && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-3.5 bg-rose-500/10 border border-rose-500/30 rounded-xl text-xs text-rose-500 font-bold flex items-center gap-2"
        >
          <AlertTriangle className="w-4 h-4 text-rose-500 flex-shrink-0" />
          <span>{errorMessage}</span>
        </motion.div>
      )}

      {/* WIZARD CONTENT STEPS */}
      <AnimatePresence mode="wait">
        {/* STEP 1: INTRO & ENROLLMENT START */}
        {step === "intro" && !mfaSettings.isEnrolled && (
          <motion.div
            key="intro"
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 10 }}
            className="space-y-5"
          >
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="p-4 bg-navy-50/70 dark:bg-navy-950/40 border border-navy-150 dark:border-navy-800 rounded-2xl space-y-2">
                <Smartphone className="w-6 h-6 text-royal-500" />
                <h4 className="text-xs font-bold text-navy-900 dark:text-white">1. Authenticator App</h4>
                <p className="text-[11px] text-navy-500">
                  Use Google Authenticator, Authy, or Microsoft Authenticator on your iOS or Android mobile device.
                </p>
              </div>

              <div className="p-4 bg-navy-50/70 dark:bg-navy-950/40 border border-navy-150 dark:border-navy-800 rounded-2xl space-y-2">
                <QrCode className="w-6 h-6 text-gold-500" />
                <h4 className="text-xs font-bold text-navy-900 dark:text-white">2. Scan QR Code</h4>
                <p className="text-[11px] text-navy-500">
                  Scan the generated QR code or enter the secret key manually into your authenticator app.
                </p>
              </div>

              <div className="p-4 bg-navy-50/70 dark:bg-navy-950/40 border border-navy-150 dark:border-navy-800 rounded-2xl space-y-2">
                <Lock className="w-6 h-6 text-emerald-500" />
                <h4 className="text-xs font-bold text-navy-900 dark:text-white">3. Verify 6-Digit Code</h4>
                <p className="text-[11px] text-navy-500">
                  Enter the dynamic 30-second token generated by your app to complete Firebase MFA registration.
                </p>
              </div>
            </div>

            <div className="flex justify-end pt-2">
              <button
                onClick={() => setStep("qr")}
                className="px-5 py-2.5 bg-royal-600 hover:bg-royal-700 text-white rounded-xl text-xs font-extrabold transition-all cursor-pointer shadow-md flex items-center gap-2"
              >
                <span>Begin Authenticator Setup</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        )}

        {/* STEP 2: QR CODE & SECRET DISPLAY */}
        {step === "qr" && (
          <motion.div
            key="qr"
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 10 }}
            className="space-y-6"
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
              {/* QR Code Container */}
              <div className="flex flex-col items-center justify-center p-6 bg-navy-950 rounded-2xl border border-navy-800 space-y-3">
                <div className="p-3 bg-white rounded-xl shadow-lg border-4 border-royal-500 flex items-center justify-center">
                  {/* Dynamic SVG QR Code rendering */}
                  <img
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(otpAuthUrl)}`}
                    alt="MFA QR Code"
                    className="w-44 h-44 object-contain"
                  />
                </div>
                <span className="text-[10px] font-mono font-bold text-navy-400 uppercase tracking-wider">
                  Scan with Google Authenticator or Authy
                </span>
              </div>

              {/* Manual Entry Key Details */}
              <div className="space-y-4">
                <div className="space-y-1">
                  <span className="text-[10px] font-mono font-bold text-navy-400 uppercase">Account Identifier</span>
                  <div className="p-2.5 bg-navy-50 dark:bg-navy-950 rounded-xl border border-navy-150 dark:border-navy-800 text-xs font-mono font-bold text-navy-900 dark:text-white">
                    {mfaSettings.accountName}
                  </div>
                </div>

                <div className="space-y-1">
                  <span className="text-[10px] font-mono font-bold text-navy-400 uppercase">Manual Secret Key</span>
                  <div className="flex items-center gap-2">
                    <div className="p-2.5 bg-navy-50 dark:bg-navy-950 rounded-xl border border-navy-150 dark:border-navy-800 text-xs font-mono font-extrabold text-gold-500 tracking-wider flex-grow">
                      {mfaSettings.secret.match(/.{1,4}/g)?.join(" ") || mfaSettings.secret}
                    </div>
                    <button
                      onClick={() => copyToClipboard(mfaSettings.secret, "secret")}
                      className="p-2.5 bg-royal-600/10 hover:bg-royal-600/20 text-royal-600 dark:text-royal-400 rounded-xl transition-colors cursor-pointer"
                      title="Copy secret key"
                    >
                      {copiedSecret ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl text-[11px] text-amber-700 dark:text-amber-300 space-y-1">
                  <span className="font-bold block flex items-center gap-1">
                    <AlertCircle className="w-3.5 h-3.5 text-amber-500" /> Important:
                  </span>
                  Do not share this secret key. It provides full access to generate TOTP authentication tokens for your account.
                </div>
              </div>
            </div>

            <div className="flex justify-between items-center pt-2 border-t border-navy-100 dark:border-navy-800">
              <button
                onClick={() => setStep("intro")}
                className="px-4 py-2 text-xs font-bold text-navy-500 hover:text-navy-700 dark:hover:text-white cursor-pointer"
              >
                Back
              </button>
              <button
                onClick={() => setStep("verify")}
                className="px-5 py-2.5 bg-royal-600 hover:bg-royal-700 text-white rounded-xl text-xs font-extrabold transition-all cursor-pointer shadow-md flex items-center gap-2"
              >
                <span>Proceed to Verification</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        )}

        {/* STEP 3: 6-DIGIT VERIFICATION */}
        {step === "verify" && (
          <motion.div
            key="verify"
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 10 }}
            className="space-y-6 max-w-md mx-auto text-center"
          >
            <div className="space-y-2">
              <div className="p-3 bg-royal-500/10 text-royal-500 rounded-full w-12 h-12 mx-auto flex items-center justify-center">
                <Key className="w-6 h-6" />
              </div>
              <h4 className="text-sm font-black text-navy-900 dark:text-white uppercase">
                Enter 6-Digit Authenticator Token
              </h4>
              <p className="text-xs text-navy-500">
                Open your authenticator app and enter the current 6-digit passcode for <strong>{mfaSettings.issuer}</strong>.
              </p>
            </div>

            {/* 6 Input Boxes */}
            <div className="flex justify-center gap-2 font-mono">
              {otpCode.map((digit, idx) => (
                <input
                  key={idx}
                  id={`mfa-otp-digit-${idx}`}
                  type="text"
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleOtpInput(idx, e.target.value)}
                  onKeyDown={(e) => handleOtpKeyDown(idx, e)}
                  onPaste={idx === 0 ? handleOtpPaste : undefined}
                  className="w-11 h-12 text-center text-lg font-black bg-navy-50 dark:bg-navy-950 border-2 border-navy-200 dark:border-navy-800 focus:border-royal-500 rounded-xl outline-none text-navy-900 dark:text-white transition-all shadow-inner"
                />
              ))}
            </div>

            <div className="flex items-center justify-between pt-4 border-t border-navy-100 dark:border-navy-800">
              <button
                onClick={() => setStep("qr")}
                className="px-4 py-2 text-xs font-bold text-navy-500 hover:text-navy-700 dark:hover:text-white cursor-pointer"
              >
                Back to QR Code
              </button>
              <button
                onClick={verifyAndEnrollMFA}
                disabled={verifying || otpCode.join("").length !== 6}
                className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-extrabold transition-all cursor-pointer shadow-md disabled:opacity-50 flex items-center gap-2"
              >
                {verifying ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Verifying Code...</span>
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-4 h-4" />
                    <span>Verify & Link Authenticator</span>
                  </>
                )}
              </button>
            </div>
          </motion.div>
        )}

        {/* STEP 4: RECOVERY CODES DISPLAY */}
        {step === "recovery" && (
          <motion.div
            key="recovery"
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 10 }}
            className="space-y-6"
          >
            <div className="space-y-1">
              <h4 className="text-sm font-black text-navy-900 dark:text-white uppercase flex items-center gap-2">
                <FileText className="w-4 h-4 text-gold-500" />
                Emergency Backup Recovery Codes
              </h4>
              <p className="text-xs text-navy-500">
                Save these emergency recovery codes. If you lose access to your phone or authenticator app, each code can be used ONCE to log into your account.
              </p>
            </div>

            <div className="p-4 bg-navy-950 rounded-2xl border border-navy-800 font-mono text-xs text-gold-400 grid grid-cols-2 gap-3">
              {mfaSettings.backupCodes.map((code, idx) => (
                <div key={idx} className="p-2 bg-navy-900 rounded-xl border border-navy-800 flex items-center justify-between">
                  <span className="text-navy-500 text-[10px]">[{idx + 1}]</span>
                  <span className="font-extrabold tracking-wider">{code}</span>
                </div>
              ))}
            </div>

            <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => copyToClipboard(mfaSettings.backupCodes.join("\n"), "recovery")}
                  className="px-3 py-2 bg-navy-100 dark:bg-navy-800 hover:bg-navy-200 dark:hover:bg-navy-700 text-navy-800 dark:text-white rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
                >
                  {copiedRecovery ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedRecovery ? "Copied All Codes" : "Copy All Codes"}</span>
                </button>

                <button
                  onClick={downloadRecoveryCodes}
                  className="px-3 py-2 bg-navy-100 dark:bg-navy-800 hover:bg-navy-200 dark:hover:bg-navy-700 text-navy-800 dark:text-white rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
                >
                  <Download className="w-3.5 h-3.5 text-royal-500" />
                  <span>Download .TXT File</span>
                </button>
              </div>

              <button
                onClick={() => setStep("active")}
                className="px-5 py-2.5 bg-royal-600 hover:bg-royal-700 text-white rounded-xl text-xs font-extrabold transition-all cursor-pointer shadow-md"
              >
                Complete Setup
              </button>
            </div>
          </motion.div>
        )}

        {/* STEP 5: ACTIVE ENROLLED DASHBOARD CARD */}
        {step === "active" && mfaSettings.isEnrolled && (
          <motion.div
            key="active"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            <div className="p-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="flex items-start gap-3">
                <div className="p-2.5 bg-emerald-500 text-white rounded-xl shadow-md">
                  <ShieldCheck className="w-6 h-6" />
                </div>
                <div className="space-y-0.5">
                  <h4 className="text-sm font-black text-navy-900 dark:text-white">
                    Authenticator Protection Enabled
                  </h4>
                  <p className="text-xs text-navy-600 dark:text-navy-300">
                    Linked to <strong>{mfaSettings.issuer}</strong> ({mfaSettings.accountName}).
                  </p>
                  <div className="text-[10px] text-navy-400 font-mono">
                    Enrolled: {new Date(mfaSettings.enrolledAt || "").toLocaleString()}
                  </div>
                </div>
              </div>

              <button
                onClick={() => setStep("recovery")}
                className="px-3.5 py-2 bg-navy-100 dark:bg-navy-800 hover:bg-navy-200 dark:hover:bg-navy-700 text-navy-800 dark:text-white rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
              >
                <FileText className="w-3.5 h-3.5 text-gold-500" />
                <span>View Recovery Codes</span>
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
