from django.db import models
from django.utils import timezone
from django.conf import settings

class ExamPrediction(models.Model):
    """
    Model representing an AI-generated exam prediction run for South African students.
    """
    CURRICULUM_CHOICES = [
        ('CAPS', 'CAPS (National Senior Certificate)'),
        ('IEB', 'IEB (Independent Examinations Board)'),
    ]
    
    PAPER_TYPE_CHOICES = [
        ('p1', 'Paper 1 (Algebra, Calculus, & Probability)'),
        ('p2', 'Paper 2 (Analytical Geometry, Trig, & Euclidean Geometry)'),
    ]

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='predictions'
    )
    curriculum = models.CharField(max_length=10, choices=CURRICULUM_CHOICES, default='CAPS')
    paper_type = models.CharField(max_length=2, choices=PAPER_TYPE_CHOICES)
    target_year = models.IntegerField(default=2026)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.student.get_full_name() or self.student.username} - {self.curriculum} Paper {self.paper_type.upper()} ({self.target_year})"


class ExamDelivery(models.Model):
    """
    Model representing multi-channel delivery (AWS SES Email & Meta WhatsApp Cloud API)
    for high-value custom predicted CAPS/IEB math exam booklets.
    """
    STATUS_CHOICES = [
        ('pending', 'Pending Dispatch in Redis/Celery queue'),
        ('sent', 'Successfully Dispatched and Delivered'),
        ('simulated', 'Simulated Local Delivery (Sandbox Mode)'),
        ('failed', 'Temporary/Permanent Delivery Failure'),
    ]

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='exam_deliveries',
        help_text="The South African Grade 10-12 or Matric Upgrade student receiving the predicted booklet."
    )
    exam_prediction = models.ForeignKey(
        ExamPrediction,
        on_delete=models.CASCADE,
        related_name='deliveries',
        help_text="The source predicted examination run generated by the AMARIS CAPS trend engine."
    )
    email_status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
        help_text="AWS SES email notification status tracker."
    )
    whatsapp_status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
        help_text="Meta WhatsApp Cloud notification status tracker."
    )
    pdf_url = models.URLField(
        max_length=500,
        help_text="Secure, HMAC-SHA256 authenticated, single-session S3 object url with student-specific watermark injection."
    )
    retry_count = models.PositiveIntegerField(
        default=0,
        help_text="Automatic Celery retry attempts counter before triggering fallback/alert channels."
    )
    sent_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="The timestamp representing when both channels successfully resolved their dispatch."
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Record ingestion timestamp in local/system database."
    )

    class Meta:
        verbose_name = "Exam Delivery Status"
        verbose_name_plural = "Exam Delivery Statuses"
        ordering = ['-created_at']

    def __str__(self):
        return f"Delivery Ref: #{self.pk} - {self.student.username} (Email: {self.email_status} | WA: {self.whatsapp_status})"

    def mark_completed(self):
        """
        Finalises transaction delivery timestamps once notifications settle successfully.
        """
        self.sent_at = timezone.now()
        self.save()
